### ISSUE TITLE
Definir no README o elemento de maior interatividade.

### ISSUE THREAD

**Issue by matheusgr** [JoseDavi/devweb#1]
Oi Davi, podes definir no README como vai funcionar o componente de maior interatividade? lembro da proposta de selecionar parte da notícia para pedir uma verificação ou atribuir uma observação de fake news / algo assim. Avançasse nessa direção? é preciso de algo que vá além de um Linke/Dislike.

**Comment by JoseDavi** [comment]
Certo vou detalhar mais. Eu segui na direção da nossa conversa, quando selecionar parte da noticia apareceria uma opção com denunciar ou fake news  e clicando nela o usuário pode preencher uma denuncia/observação sobre o trecho selecionado, seria isso? estou aberto para outras modificações, a possibilidade de comentários, ou outras funcionalidades.
