### ISSUE TITLE
Funções de deslike e like poderiam ser unidas

### ISSUE THREAD

**Issue by mateusoliveira2** [JoseDavi/devweb#5]
As funções de deslike e like poderiam se transformar em uma apenas, recebendo se seria deslike ou like por parametro já que os métodos são bem parecidos.

![image](https://user-images.githubusercontent.com/33286442/152616000-e1cfde20-449a-46e3-a864-0f9f9d368b77.png)

**Comment by JoseDavi** [comment]
Boa ideia, ajustado!
