### ISSUE TITLE
Feeback

### ISSUE THREAD

**Issue by viniciusbds** [JoseDavi/devweb#6]
Primeiramente, essa issue é mais um feedback.
Segundamente, o palmeiras.

Até onde vi o projeto está bastante adiantado, incluindo requisições ao servidor usando **useEffect**. Em relação a entrega atual, o projeto contem um componente pai **News** com estados proprios que são passados para o componente filho **NewsCard** via props.  tudo certo ;)

**Comment by JoseDavi** [comment]
Primeiramente, vlw!
Segundamente, o palmeiras.
