### ISSUE TITLE
Organização das pastas do componentes

### ISSUE THREAD

**Issue by talitagaldino** [JoseDavi/devweb#7]
Tá bem legal o projeto, é mais uma sugestão mesmo. Vi que você colocou pages/news/components, meu conselho é que você deixe a página de componentes no mesmo local onde está a pasta pages pois assim você pode reutilizar mais facilmente o componente em várias pastas, se o projeto fica muito grande e você cria uma pasta de componentes dentro da pasta de cada página, em algum momento você vai se perder e não encontrar componentes.

**Comment by JoseDavi** [comment]
Entendi a sugestão, mas no meu caso eu optei por essa arquitetura por conta que os componentes que estão dentro das paginas são os componentes que pertencem unicamente a elas, por exemplo nesse pages/news/components  são os que pertencem a news e não vão ser usados por mais ninguém no projeto, os componentes que podem ser usados por outros ficam dentro de shared/components, como meu header e minha paginação até agora.
